
-- Create Table for Products in master schema
CREATE TABLE IF NOT EXISTS master.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(50) UNIQUE NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    brand VARCHAR(100),
    division VARCHAR(100),
    price DECIMAL(15,2) DEFAULT 0,
    stock INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    company_id VARCHAR(50) DEFAULT 'ID001',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_products_code ON master.ref_products(product_code);
CREATE INDEX IF NOT EXISTS idx_products_category ON master.ref_products(category);

-- Enable RLS if needed (but currently we use service role in backend)
-- ALTER TABLE master.ref_products ENABLE ROW LEVEL SECURITY;
